# Copyright 2025 Digital Bazaar, Inc.
# SPDX-License-Identifier: BSD-3-Clause

# OSV-Scanner PR scanning reusable workflow, can be used as a PR action to
# detect new vulnerabilities being introduced.
name: Use OSV to do SCA on `main`

on:
  workflow_call:

jobs:
  ## run the following only on the main branch
  osv-scan-main:
    if: github.event_name == 'push' || github.event_name == 'schedule'
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - name: Set current date to NOW env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          submodules: false
          # Do persist credentials, as we need it for the git checkout later
          persist-credentials: true
      - name: "Checkout base branch"
        run: |
          git checkout $GITHUB_BASE_REF
          git submodule update --recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Does package-lock.json exist?
        id: has_package_lock
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: "package-lock.json"
      - name: Generate `package-lock.json` from authorized sources
        if: steps.has_package_lock.outputs.files_exists == 'false'
        run: |
          npm install --package-lock-only --ignore-scripts
      - name: "Run scanner on existing code and generate Markdown"
        uses: google/osv-scanner-action/osv-scanner-action@c51854704019a247608d928f370c98740469d4b5 # v2.3.5
        continue-on-error: true
        with:
          scan-args: |-
            --format=markdown
            --output=results.md
            --lockfile=package-lock.json
      - name: Store results in variable
        id: results
        uses: juliangruber/read-file-action@271ff311a4947af354c6abcd696a306553b9ec18 # v1.1.8
        with:
          path: results.md
          trim: true
      # Run npm audit and npm list to build up additional report explanations
      - name: npm audit
        id: npm_audit
        shell: bash
        run: |
          echo 'result=$(npm audit --json)' >> $GITHUB_OUTPUT
        continue-on-error: true
      # Use `jq` to create a Markdown table of the findings
      - name: npm audit
        id: audit_report
        shell: bash
        run: |
          AUDIT=$(echo "${{ toJson(steps.npm_audit.outputs.result) }}" | jq -r '
            "| Severity | Name | Version | Fix Available |",
            "| --- | --- | --- | --- |",
            (.vulnerabilities | to_entries | .[] |
              "| \(.value.severity) | \(.key) | \(.value.range) | \(.value.fixAvailable.version) |"
            )')
          # Use a random delimiter to capture the multi-line output
          delimiter=$(openssl rand -hex 8)
          echo "result<<$delimiter" >> $GITHUB_OUTPUT
          echo "$AUDIT" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
        continue-on-error: true
      # Generate a tree/list based on the vulnerable package names
      - name: npm list vulnerable dependencies
        id: list_report
        shell: bash
        run: |
          DEPS=$(echo "${{ toJSON(steps.npm_audit.outputs.result) }}" | jq -r '[.vulnerabilities | to_entries[] | .key] | join(" ")')
          LIST=$(npm list $DEPS --json --package-lock-only | jq -r '
            def walk_tree(prefix):
              to_entries | map(
                "\(prefix)\(.key)@\(.value.version)\n" +
                if .value.dependencies then
                  (.value.dependencies | walk_tree("  " + prefix))
                else
                  ""
                end
              ) | join("");
            .dependencies | walk_tree("* ")')
          # Use a random delimiter to capture the multi-line output
          delimiter=$(openssl rand -hex 8)
          echo "result<<$delimiter" >> $GITHUB_OUTPUT
          echo "$LIST" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
        continue-on-error: true
        # Combine the two Markdown reports into one for use elsewhere
      - name: combine npm audit/list reports
        id: combined_report
        shell: bash
        run: |
          # Use a random delimiter to capture the multi-line output
          delimiter=$(openssl rand -hex 8)
          echo "result<<$delimiter" >> $GITHUB_OUTPUT
          echo "### npm audit

          ${{ steps.audit_report.outputs.result }}

          ### npm list

          ${{ steps.list_report.outputs.result }}
          " >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT

      # Create the OSV label if it doesn't already exist
      - name: Create OSV label if it doesn't exist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh label create OSV --color 033f72 --description "Vulnerabilities found by https://osv.dev/" || true
      - name: Find the most recent OSV issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: latest_issue
        # Note: this only finds the latest `OSV` labeled issue, so if there are
        # more than one OSV issue, those will be left alone.
        run: |
          ISSUE_NUM=$(gh issue list --search 'label:OSV sort:created-desc' --limit 1 --json number --jq .[].number)
          echo "content=$ISSUE_NUM" >> $GITHUB_OUTPUT
      - name: Update existing issue if vulnerabilities
        if: ${{ steps.latest_issue.outputs.content != '' && !contains(steps.results.outputs.content, 'No issues found') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY: ${{ steps.results.outputs.content }}
          LATEST_ISSUE: ${{ steps.latest_issue.outputs.content }}
        run: |
          gh issue edit ${LATEST_ISSUE} --title "Vulnerabilities as of ${NOW}" --body "${ISSUE_BODY} ${{ steps.audit_list_report.outputs.result }}"
      - name: Close existing issue if no vulnerabilities
        if: ${{ steps.latest_issue.outputs.content != '' && contains(steps.results.outputs.content, 'No issues found') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LATEST_ISSUE: ${{ steps.latest_issue.outputs.content }}
          COMMENT: ${{ steps.results.outputs.content }}
        run: |
          gh issue close ${LATEST_ISSUE} --comment "${COMMENT} ${{ steps.audit_list_report.outputs.result }}"
      - name: Create issue from results
        if: ${{ steps.latest_issue.outputs.content == '' && !contains(steps.results.outputs.content, 'No issues found') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY: ${{ steps.results.outputs.content }}
        run: |
          gh issue create --title "Vulnerabilities as of ${NOW}" --body "${ISSUE_BODY} ${{ steps.audit_list_report.outputs.result }}" --label OSV
