# Copyright 2025 Digital Bazaar, Inc.
# SPDX-License-Identifier: BSD-3-Clause

# OSV-Scanner PR scanning reusable workflow, can be used as a PR action to
# detect new vulnerabilities being introduced.
name: Use OSV to do SCA on `main`

on:
  workflow_call:

jobs:
  ## run the following only on the main branch
  osv-scan-main:
    if: github.event_name == 'push' || github.event_name == 'schedule'
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - name: Set current date to NOW env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          submodules: false
          # Do persist credentials, as we need it for the git checkout later
          persist-credentials: true
      - name: Scan branch
        id: scan
        uses: $/.github/actions/scan-branch
        with:
          ref: ${{ github.sha }}
          node-version: ${{ matrix.node-version }}
          warning-label: "the scan"

      # Create the OSV label if it doesn't already exist
      - name: Create OSV label if it doesn't exist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh label create OSV --color 033f72 --description "Vulnerabilities found by https://osv.dev/" || true
      - name: Find the most recent OSV issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: latest_issue
        # Note: this only finds the latest `OSV` labeled issue, so if there are
        # more than one OSV issue, those will be left alone.
        run: |
          ISSUE_NUM=$(gh issue list --search 'label:OSV sort:created-desc' --limit 1 --json number --jq .[].number)
          echo "content=$ISSUE_NUM" >> $GITHUB_OUTPUT
      - name: Update existing issue if vulnerabilities
        if: ${{ steps.latest_issue.outputs.content != '' && !contains(steps.scan.outputs.osv-result, 'No issues found') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY: ${{ steps.scan.outputs.osv-result }}
          LATEST_ISSUE: ${{ steps.latest_issue.outputs.content }}
          STEPS_SCAN_OUTPUTS_AUDIT_LIST_RESULT: ${{ steps.scan.outputs.audit-list-result }}
        run: |
          gh issue edit ${LATEST_ISSUE} --title "Vulnerabilities as of ${NOW}" --body "${ISSUE_BODY}"$'\n\n'"${STEPS_SCAN_OUTPUTS_AUDIT_LIST_RESULT}"
      - name: Close existing issue if no vulnerabilities
        if: ${{ steps.latest_issue.outputs.content != '' && contains(steps.scan.outputs.osv-result, 'No issues found') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LATEST_ISSUE: ${{ steps.latest_issue.outputs.content }}
          COMMENT: ${{ steps.scan.outputs.osv-result }}
          STEPS_SCAN_OUTPUTS_AUDIT_LIST_RESULT: ${{ steps.scan.outputs.audit-list-result }}
        run: |
          gh issue close ${LATEST_ISSUE} --comment "${COMMENT}"$'\n\n'"${STEPS_SCAN_OUTPUTS_AUDIT_LIST_RESULT}"
      - name: Create issue from results
        if: ${{ steps.latest_issue.outputs.content == '' && !contains(steps.scan.outputs.osv-result, 'No issues found') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY: ${{ steps.scan.outputs.osv-result }}
          STEPS_SCAN_OUTPUTS_AUDIT_LIST_RESULT: ${{ steps.scan.outputs.audit-list-result }}
        run: |
          gh issue create --title "Vulnerabilities as of ${NOW}" --body "${ISSUE_BODY}"$'\n\n'"${STEPS_SCAN_OUTPUTS_AUDIT_LIST_RESULT}" --label OSV
