# Copyright 2025 Digital Bazaar, Inc.
# SPDX-License-Identifier: BSD-3-Clause

# OSV-Scanner PR scanning reusable workflow, can be used as a PR action to
# detect new vulnerabilities being introduced.
name: Use OSV to do SCA on a PR

on:
  workflow_call:

jobs:
  ## run the following on PRs
  osv-scan-pr:
    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          submodules: false
          # Do persist credentials, as we need it for the git checkout later
          persist-credentials: true
      - name: "Checkout base branch"
        run: |
          git checkout $GITHUB_BASE_REF
          git submodule update --recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Does package-lock.json exist?
        id: base_package_lock
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: "package-lock.json"
      - name: Generate `package-lock.json`
        if: steps.base_package_lock.outputs.files_exists == 'false'
        run: |
          npm install --package-lock-only --ignore-scripts
      - name: "Run scanner on existing code and generate Markdown"
        uses: google/osv-scanner-action/osv-scanner-action@c51854704019a247608d928f370c98740469d4b5 # v2.3.5
        continue-on-error: true
        with:
          scan-args: |-
            --format=markdown
            --output=old-results.md
            --lockfile=package-lock.json
      - name: Store old results in variable
        continue-on-error: true
        id: old
        uses: juliangruber/read-file-action@271ff311a4947af354c6abcd696a306553b9ec18 # v1.1.8
        with:
          path: old-results.md
      # Run npm audit and npm list to build up additional report explanations
      - name: npm audit
        id: npm_audit_base
        shell: bash
        run: |
          echo 'result=$(npm audit --json)' >> $GITHUB_OUTPUT
        continue-on-error: true
      # Use `jq` to create a Markdown table of the findings
      - name: npm audit
        id: audit_report_base
        shell: bash
        run: |
          AUDIT=$(echo "${{ toJson(steps.npm_audit_base.outputs.result) }}" | jq -r '
            "| Severity | Name | Version | Fix Available |",
            "| --- | --- | --- | --- |",
            (.vulnerabilities | to_entries | .[] |
              "| \(.value.severity) | \(.key) | \(.value.range) | \(.value.fixAvailable.version) |"
            )')
          # Use a random delimiter to capture the multi-line output
          delimiter=$(openssl rand -hex 8)
          echo "result<<$delimiter" >> $GITHUB_OUTPUT
          echo "$AUDIT" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
        continue-on-error: true
      # Generate a tree/list based on the vulnerable package names
      - name: npm list vulnerable dependencies
        id: list_report_base
        shell: bash
        run: |
          DEPS=$(echo "${{ toJSON(steps.npm_audit_base.outputs.result) }}" | jq -r '[.vulnerabilities | to_entries[] | .key] | join(" ")')
          LIST=$(npm list $DEPS --json --package-lock-only | jq -r '
            def walk_tree(prefix):
              to_entries | map(
                "\(prefix)\(.key)@\(.value.version)\n" +
                if .value.dependencies then
                  (.value.dependencies | walk_tree("  " + prefix))
                else
                  ""
                end
              ) | join("");
            .dependencies | walk_tree("* ")')
          # Use a random delimiter to capture the multi-line output
          delimiter=$(openssl rand -hex 8)
          echo "result<<$delimiter" >> $GITHUB_OUTPUT
          echo "$LIST" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
        continue-on-error: true
        # Combine the two Markdown reports into one for use elsewhere
      - name: combine npm audit/list reports
        id: old_audit_list_report
        shell: bash
        run: |
          # Use a random delimiter to capture the multi-line output
          delimiter=$(openssl rand -hex 8)
          echo "result<<$delimiter" >> $GITHUB_OUTPUT
          echo "### npm audit

          ${{ steps.audit_report_base.outputs.result }}

          ### npm list

          ${{ steps.list_report_base.outputs.result }}
          " >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT

      # --- run the same on the current branch ---
      - name: "Checkout current branch"
        # Use -f in case any changes were made by osv-scanner (there should be no changes)
        run: |
          git checkout -f $GITHUB_SHA
          git submodule update --recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Does package-lock.json exist?
        id: current_package_lock
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: "package-lock.json"
      - name: Generate `package-lock.json`
        if: steps.current_package_lock.outputs.files_exists == 'false'
        run: |
          npm install --package-lock-only --ignore-scripts
      # post the generated markdown as a comment
      - name: "Run scanner on new code and generate Markdown"
        uses: google/osv-scanner-action/osv-scanner-action@c51854704019a247608d928f370c98740469d4b5 # v2.3.5
        with:
          scan-args: |-
            --format=markdown
            --output=new-results.md
            --lockfile=package-lock.json
        continue-on-error: true
      - name: Store new results in variable
        id: new
        uses: juliangruber/read-file-action@271ff311a4947af354c6abcd696a306553b9ec18 # v1.1.8
        with:
          path: new-results.md

      # Run npm audit and npm list to build up additional report explanations
      - name: npm audit
        id: npm_audit
        shell: bash
        run: |
          echo 'result=$(npm audit --json)' >> $GITHUB_OUTPUT
        continue-on-error: true
      # Use `jq` to create a Markdown table of the findings
      - name: npm audit
        id: audit_report
        shell: bash
        run: |
          AUDIT=$(echo "${{ toJson(steps.npm_audit.outputs.result) }}" | jq -r '
            "| Severity | Name | Version | Fix Available |",
            "| --- | --- | --- | --- |",
            (.vulnerabilities | to_entries | .[] |
              "| \(.value.severity) | \(.key) | \(.value.range) | \(.value.fixAvailable.version) |"
            )')
          # Use a random delimiter to capture the multi-line output
          delimiter=$(openssl rand -hex 8)
          echo "result<<$delimiter" >> $GITHUB_OUTPUT
          echo "$AUDIT" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
        continue-on-error: true
      # Generate a tree/list based on the vulnerable package names
      - name: npm list vulnerable dependencies
        id: list_report
        shell: bash
        run: |
          DEPS=$(echo "${{ toJSON(steps.npm_audit.outputs.result) }}" | jq -r '[.vulnerabilities | to_entries[] | .key] | join(" ")')
          LIST=$(npm list $DEPS --json --package-lock-only | jq -r '
            def walk_tree(prefix):
              to_entries | map(
                "\(prefix)\(.key)@\(.value.version)\n" +
                if .value.dependencies then
                  (.value.dependencies | walk_tree("  " + prefix))
                else
                  ""
                end
              ) | join("");
            .dependencies | walk_tree("* ")')
          # Use a random delimiter to capture the multi-line output
          delimiter=$(openssl rand -hex 8)
          echo "result<<$delimiter" >> $GITHUB_OUTPUT
          echo "$LIST" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
        continue-on-error: true
        # Combine the two Markdown reports into one for use elsewhere
      - name: combine npm audit/list reports
        id: new_audit_list_report
        shell: bash
        run: |
          # Use a random delimiter to capture the multi-line output
          delimiter=$(openssl rand -hex 8)
          echo "result<<$delimiter" >> $GITHUB_OUTPUT
          echo "### npm audit

          ${{ steps.audit_report.outputs.result }}

          ### npm list

          ${{ steps.list_report.outputs.result }}
          " >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT


      # Combine OSV, npm audit, and npm list output into a single comment
      - name: Add a comment containing OSV, npm audit, and npm list output
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          comment-tag: action_report
          message: |
            ## Vulnerability results from base branch
            ${{ steps.old.outputs.content }}

            ${{ steps.old_audit_list_report.outputs.result }}
            ---

            ## Vulnerability results from current PR branch
            ${{ steps.new.outputs.content }}

            ${{ steps.new_audit_list_report.outputs.result }}
